spring:
  profiles:
    active:
      local

  datasource:
    url: jdbc:mysql://localhost:3306/vicky
    username: root
    password: uhUH1029
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Hibernate 자동 DDL 생성 옵션

#    properties:
#      hibernate:
#        show_sql: true  # SQL 쿼리 출력 여부 - 프로덕션 환경에서는 보안, 성능 이슈로 비활성화
#        format_sql: true  # SQL 쿼리 포맷팅 여부 - 프로덕션 환경에서는 보안, 성능 고려해서 사용
#        use_sql_comments: true  # SQL 쿼리 주석 사용 여부 - 보안, 성능 이슈
#
#logging.level:
#  org.hibernate.SQL: debug  # Hibernate SQL 쿼리를 debug 레벨로 설정하여 로깅합니다.
#  org.hibernate.orm.jdbc.bind: trace  # 스프링 부트 3.x, Hibernate 6.x에서 JDBC 바인딩을 trace 레벨로 설정합니다.
#  org.hibernate.type: trace  # 스프링 부트 2.x, Hibernate 5.x에서 타입 변환을 trace 레벨로 설정합니다.

# JWT 토큰 서명을 위한 비밀 키
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==